### ISSUE TITLE
not actually an issue

### ISSUE THREAD

**Issue by gilesbradshaw** [AaltoIIC/OPC-UA-GraphQL-Wrapper#2]
I played with something like this a while ago and thought you might like to look at it..

the code is on here https://github.com/ua-ql

and if you browse here you get a demo https://gilesbradshaw.github.io/apollo-client/#/boilers/ns=4;i=1241

It's talking to a public opc server and subscribing to changes.  If you click the command button it will change the running state of the tank...

If you click on home you can then browse round the entire opc server (using graphql)

(it's kicking off a server on heroku when it first starts so there can be a delay and if it isn't working at all it will be because it's on the free tier and only runs for so many houyrs a day

best wishes :)

**Comment by rrikooo** [comment]
Thank you for sharing this project with us!

**Comment by juusoautiosalo** [comment]
Closing this issue now as it is not actually an issue.

@gilesbradshaw please post this to Discussions if you like.
